### ISSUE TITLE
Error obtaning accounts

### ISSUE THREAD

**Issue by ysilvela** [mateodelnorte/coinbase#18]
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/openshift/5562dcd5500446389000024c/app-root/
runtime/repo/node_modules/coinbase/lib/model/AccountBase.js:9:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mateodelnorte** [comment]
You're using the new, coinbase supplied version of this module. You can direct your issue here: https://github.com/coinbase/coinbase-node
